# Generated by Django 3.2.5 on 2021-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_sno_comments_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=300000000),
        ),
    ]
